### PR TITLE
Auto download and validate latest server JAR

### PR DESCRIPTION
**Pull request by chrisys**
This automatically finds and downloads the latest version of the server if we don't already have it. It also validates the JAR on disk against the specified sha256 hash in case the download failed.

### CODE REVIEW

**Comment by chrisys** [comment]
@AlexProgrammerDE I think I'm done with this PR now, let me know what you think 👍

**Comment by AlexProgrammerDE** [comment]
grafik

@chrisys i think we could make use of the version api and also get the newest minecraft version that they support.

**Comment by chrisys** [comment]
Sure, I didn't know that one existed - I'll add that

**Comment by chrisys** [comment]
@AlexProgrammerDE should be good to go now, I've started playing the game instead of working on the code now 😂

**Review by AlexProgrammerDE — APPROVED** [review]
@chrisys haha. Ok im gonna merge this now.

**Comment by johanjpk** [comment]
How do I apply this on my running server?

**Comment by AlexProgrammerDE** [comment]
@johanjpk just git clone and balena push the repository again and it will update your raspberry pi.

**Comment by johanjpk** [comment]
Sorry still unclear to me. I'd like to keep the world data.

**Comment by wsteven-son** [comment]
@johanjpk on your running server, copy serverfiles folder (within mc-server folder). Next, git clone the updated balena-minecraft-server files and drop your serverfiles folder into this folder in the same spot. Then use balena push to release this updated version to your balena cloud which will update your server

**Pull request merged**
